import type { ShellData } from '../types/shell'

export const fallbackShellData: ShellData = {
  meta: {
    teamName: 'Team 4',
    workspaceName: 'TeamPulse workspace',
    currentPhase: 'Phase 0 -> Phase 1',
    deadline: '2026-06-09',
    stack: ['React SPA', 'Tailwind CSS', 'Spring Boot', 'MySQL'],
    deployment: {
      frontend: 'Vercel Production',
      backend: 'AWS App Runner or Elastic Beanstalk',
      database: 'AWS RDS MySQL',
    },
  },
  milestones: [
    { date: '2026-04-07', label: '아키텍처 + ERD 확정' },
    { date: '2026-04-14', label: 'API 명세 + 와이어프레임 완료' },
    { date: '2026-04-21', label: '선후행 관계 PoC 검증' },
    { date: '2026-04-28', label: '설계 문서 최종 제출' },
  ],
  tasks: [
    {
      id: 1,
      title: 'ERD 초안 확정',
      owner: '한지훈',
      status: 'DOING',
      dueDate: '2026-04-07',
      priority: 'HIGH',
      blockers: [],
      next: ['API 명세 1차 작성'],
      note: '핵심 엔티티 정리 완료. team과 project 단일화 여부만 남음.',
    },
    {
      id: 2,
      title: 'API 명세 1차 작성',
      owner: '이주호',
      status: 'TODO',
      dueDate: '2026-04-10',
      priority: 'HIGH',
      blockers: ['ERD 초안 확정'],
      next: ['프론트 모킹 데이터 교체'],
      note: '인증, 팀, 태스크, 회의, 리포트 범위를 1차 고정.',
    },
    {
      id: 3,
      title: '대시보드 UI 셸 구현',
      owner: '박태희',
      status: 'DOING',
      dueDate: '2026-04-09',
      priority: 'MEDIUM',
      blockers: [],
      next: ['리스크 카드 연결'],
      note: '현재 프론트 MVP를 Tailwind 기준으로 재정렬하는 작업이다.',
    },
    {
      id: 4,
      title: '리스크 규칙 임계값 초안',
      owner: '이주호',
      status: 'TODO',
      dueDate: '2026-04-12',
      priority: 'MEDIUM',
      blockers: ['ERD 초안 확정'],
      next: ['대시보드 신호 반영'],
      note: '진행 정체 / 병목 / 일정 지연 위험을 우선 정의.',
    },
    {
      id: 5,
      title: '설계 점검 회의록 정리',
      owner: '박태희',
      status: 'DONE',
      dueDate: '2026-04-05',
      priority: 'LOW',
      blockers: [],
      next: [],
      note: '액션아이템을 태스크로 연결하는 흐름 검증 완료.',
    },
  ],
  riskSignals: [
    {
      id: 1,
      severity: 'CRITICAL',
      title: '선행 태스크 지연 시 API 작업이 함께 밀릴 수 있습니다.',
      body: 'ERD 초안 확정이 늦어지면 API 명세와 보드 연동 작업이 연쇄적으로 대기 상태가 됩니다.',
      action: 'ERD 범위를 줄이거나 API 초안을 병렬로 분리 작성',
    },
    {
      id: 2,
      severity: 'WARNING',
      title: '백엔드 준비 작업이 한 명에게 몰리고 있습니다.',
      body: '현재 인증, 팀, DB 스키마 논의가 모두 한지훈 중심으로 쏠려 있습니다.',
      action: 'API 문서화와 DB 제약조건 리뷰를 분담',
    },
    {
      id: 3,
      severity: 'INFO',
      title: '회의 기록과 액션아이템 연결 흐름은 비교적 안정적입니다.',
      body: '회의 화면 구조와 보고서 섹션 정의가 이미 문서화되어 있어 구현 진입 장벽이 낮습니다.',
      action: '백엔드 엔드포인트 확정 후 바로 화면 연결 가능',
    },
  ],
  meetings: [
    {
      id: 1,
      title: '2단계 설계 점검 회의',
      time: '2026-04-06 19:00',
      agenda: 'ERD, API 명세, 선후행 관계 표현 방식 확정',
      decisions: ['team = project 단순화', '리스크 5종 유지', 'React + Spring 분리 구조 유지'],
      actions: ['ERD 초안 확정', 'API 10개 이상 엔드포인트 명세', '프론트 셸 구현'],
    },
    {
      id: 2,
      title: '구현 진입 회의',
      time: '2026-04-09 18:30',
      agenda: 'Phase 0/1 실제 착수 범위 확인',
      decisions: ['인증/팀/태스크를 첫 목표로 고정'],
      actions: ['백엔드 공통 응답 구조 작성', '프론트 API 연결'],
    },
  ],
  activities: [
    {
      id: 1,
      actor: 'Codex',
      at: '2026-04-05 22:20',
      summary: 'React 프론트와 Spring Boot 백엔드 골격을 생성했다.',
    },
    {
      id: 2,
      actor: 'Codex',
      at: '2026-04-05 21:40',
      summary: '시스템 아키텍처, DB, API, UI, 로드맵 문서를 코텍스 워크 플레이스에 작성했다.',
    },
    {
      id: 3,
      actor: 'TeamPulse',
      at: '2026-04-05 19:10',
      summary: '기획서와 SRS 기준본을 확정했다.',
    },
  ],
  reports: [
    { id: 1, label: '설계 단계 팀 요약', range: '2026-04-01 ~ 2026-04-05', status: 'READY' },
    { id: 2, label: '주간 활동 로그', range: '2026-04-06 ~ 2026-04-12', status: 'GENERATING' },
    { id: 3, label: '발표 제출용 프로젝트 리포트', range: '2026-04-01 ~ 2026-06-09', status: 'FAILED' },
  ],
}
